export const countries = [
  { name: "Afghanistan", flag: "🇦🇫", phone: "+93", code: "AF" },
  { name: "Albania", flag: "🇦🇱", phone: "+355", code: "AL" },
  { name: "Algeria", flag: "🇩🇿", phone: "+213", code: "DZ" },
  { name: "Andorra", flag: "🇦🇩", phone: "+376", code: "AD" },
  { name: "Angola", flag: "🇦🇴", phone: "+244", code: "AO" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", phone: "+1", code: "AG" },
  { name: "Argentina", flag: "🇦🇷", phone: "+54", code: "AR" },
  { name: "Armenia", flag: "🇦🇲", phone: "+374", code: "AM" },
  { name: "Australia", flag: "🇦🇺", phone: "+61", code: "AU" },
  { name: "Austria", flag: "🇦🇹", phone: "+43", code: "AT" },
  { name: "Azerbaijan", flag: "🇦🇿", phone: "+994", code: "AZ" },
  { name: "Bahamas", flag: "🇧🇸", phone: "+1", code: "BS" },
  { name: "Bahrain", flag: "🇧🇭", phone: "+973", code: "BH" },
  { name: "Bangladesh", flag: "🇧🇩", phone: "+880", code: "BD" },
  { name: "Barbados", flag: "🇧🇧", phone: "+1", code: "BB" },
  { name: "Belarus", flag: "🇧🇾", phone: "+375", code: "BY" },
  { name: "Belgium", flag: "🇧🇪", phone: "+32", code: "BE" },
  { name: "Belize", flag: "🇧🇿", phone: "+501", code: "BZ" },
  { name: "Benin", flag: "🇧🇯", phone: "+229", code: "BJ" },
  { name: "Bhutan", flag: "🇧🇹", phone: "+975", code: "BT" },
  { name: "Bolivia", flag: "🇧🇴", phone: "+591", code: "BO" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", phone: "+387", code: "BA" },
  { name: "Botswana", flag: "🇧🇼", phone: "+267", code: "BW" },
  { name: "Brazil", flag: "🇧🇷", phone: "+55", code: "BR" },
  { name: "Brunei", flag: "🇧🇳", phone: "+673", code: "BN" },
  { name: "Bulgaria", flag: "🇧🇬", phone: "+359", code: "BG" },
  { name: "Burkina Faso", flag: "🇧🇫", phone: "+226", code: "BF" },
  { name: "Burundi", flag: "🇧🇮", phone: "+257", code: "BI" },
  { name: "Cabo Verde", flag: "🇨🇻", phone: "+238", code: "CV" },
  { name: "Cambodia", flag: "🇰🇭", phone: "+855", code: "KH" },
  { name: "Cameroon", flag: "🇨🇲", phone: "+237", code: "CM" },
  { name: "Canada", flag: "🇨🇦", phone: "+1", code: "CA" },
  { name: "Central African Republic", flag: "🇨🇫", phone: "+236", code: "CF" },
  { name: "Chad", flag: "🇹🇩", phone: "+235", code: "TD" },
  { name: "Chile", flag: "🇨🇱", phone: "+56", code: "CL" },
  { name: "China", flag: "🇨🇳", phone: "+86", code: "CN" },
  { name: "Colombia", flag: "🇨🇴", phone: "+57", code: "CO" },
  { name: "Comoros", flag: "🇰🇲", phone: "+269", code: "KM" },
  { name: "Congo", flag: "🇨🇩", phone: "+243", code: "CD" },
  { name: "Costa Rica", flag: "🇨🇷", phone: "+506", code: "CR" },
  { name: "Croatia", flag: "🇭🇷", phone: "+385", code: "HR" },
  { name: "Cuba", flag: "🇨🇺", phone: "+53", code: "CU" },
  { name: "Cyprus", flag: "🇨🇾", phone: "+357", code: "CY" },
  { name: "Czech Republic", flag: "🇨🇿", phone: "+420", code: "CZ" },
  { name: "Denmark", flag: "🇩🇰", phone: "+45", code: "DK" },
  { name: "Djibouti", flag: "🇩🇯", phone: "+253", code: "DJ" },
  { name: "Dominica", flag: "🇩🇲", phone: "+1", code: "DM" },
  { name: "Dominican Republic", flag: "🇩🇴", phone: "+1", code: "DO" },
  { name: "East Timor", flag: "🇹🇱", phone: "+670", code: "TL" },
  { name: "Ecuador", flag: "🇪🇨", phone: "+593", code: "EC" },
  { name: "Egypt", flag: "🇪🇬", phone: "+20", code: "EG" },
  { name: "El Salvador", flag: "🇸🇻", phone: "+503", code: "SV" },
  { name: "Equatorial Guinea", flag: "🇬🇳", phone: "+240", code: "GQ" },
  { name: "Eritrea", flag: "🇪🇷", phone: "+291", code: "ER" },
  { name: "Estonia", flag: "🇪🇪", phone: "+372", code: "EE" },
  { name: "Eswatini", flag: "🇸🇿", phone: "+268", code: "SZ" },
  { name: "Ethiopia", flag: "🇪🇹", phone: "+251", code: "ET" },
  { name: "Fiji", flag: "🇫🇯", phone: "+679", code: "FJ" },
  { name: "Finland", flag: "🇫🇮", phone: "+358", code: "FI" },
  { name: "France", flag: "🇫🇷", phone: "+33", code: "FR" },
  { name: "Gabon", flag: "🇬🇦", phone: "+241", code: "GA" },
  { name: "Gambia", flag: "🇬🇲", phone: "+220", code: "GM" },
  { name: "Georgia", flag: "🇬🇪", phone: "+995", code: "GE" },
  { name: "Germany", flag: "🇩🇪", phone: "+49", code: "DE" },
  { name: "Ghana", flag: "🇬🇭", phone: "+233", code: "GH" },
  { name: "Greece", flag: "🇬🇷", phone: "+30", code: "GR" },
  { name: "Grenada", flag: "🇬🇩", phone: "+1", code: "GD" },
  { name: "Guatemala", flag: "🇬🇹", phone: "+502", code: "GT" },
  { name: "Guinea", flag: "🇬🇳", phone: "+224", code: "GN" },
  { name: "Guinea-Bissau", flag: "🇬🇼", phone: "+245", code: "GW" },
  { name: "Guyana", flag: "🇬🇾", phone: "+592", code: "GY" },
  { name: "Haiti", flag: "🇭🇹", phone: "+509", code: "HT" },
  { name: "Honduras", flag: "🇭🇳", phone: "+504", code: "HN" },
  { name: "Hungary", flag: "🇭🇺", phone: "+36", code: "HU" },
  { name: "Iceland", flag: "🇮🇸", phone: "+354", code: "IS" },
  { name: "India", flag: "🇮🇳", phone: "+91", code: "IN" },
  { name: "Indonesia", flag: "🇮🇩", phone: "+62", code: "ID" },
  { name: "Iran", flag: "🇮🇷", phone: "+98", code: "IR" },
  { name: "Iraq", flag: "🇮🇶", phone: "+964", code: "IQ" },
  { name: "Ireland", flag: "🇮🇪", phone: "+353", code: "IE" },
  { name: "Israel", flag: "🇮🇱", phone: "+972", code: "IL" },
  { name: "Italy", flag: "🇮🇹", phone: "+39", code: "IT" },
  { name: "Jamaica", flag: "🇯🇲", phone: "+1", code: "JM" },
  { name: "Japan", flag: "🇯🇵", phone: "+81", code: "JP" },
  { name: "Jordan", flag: "🇯🇴", phone: "+962", code: "JO" },
  { name: "Kazakhstan", flag: "🇰🇿", phone: "+7", code: "KZ" },
  { name: "Kenya", flag: "🇰🇪", phone: "+254", code: "KE" },
  { name: "Kiribati", flag: "🇰🇮", phone: "+686", code: "KI" },
  { name: "Korea, North", flag: "🇰🇵", phone: "+850", code: "KP" },
  { name: "Korea, South", flag: "🇰🇷", phone: "+82", code: "KR" },
  { name: "Kosovo", flag: "🇽🇰", phone: "+383", code: "XK" },
  { name: "Kuwait", flag: "🇰🇼", phone: "+965", code: "KW" },
  { name: "Kyrgyzstan", flag: "🇰🇬", phone: "+996", code: "KG" },
  { name: "Laos", flag: "🇱🇦", phone: "+856", code: "LA" },
  { name: "Latvia", flag: "🇱🇻", phone: "+371", code: "LV" },
  { name: "Lebanon", flag: "🇱🇧", phone: "+961", code: "LB" },
  { name: "Lesotho", flag: "🇱🇸", phone: "+266", code: "LS" },
  { name: "Liberia", flag: "🇱🇷", phone: "+231", code: "LR" },
  { name: "Libya", flag: "🇱🇾", phone: "+218", code: "LY" },
  { name: "Liechtenstein", flag: "🇱🇮", phone: "+423", code: "LI" },
  { name: "Lithuania", flag: "🇱🇹", phone: "+370", code: "LT" },
  { name: "Luxembourg", flag: "🇱🇺", phone: "+352", code: "LU" },
  { name: "Madagascar", flag: "🇲🇬", phone: "+261", code: "MG" },
  { name: "Malawi", flag: "🇲🇼", phone: "+265", code: "MW" },
  { name: "Malaysia", flag: "🇲🇾", phone: "+60", code: "MY" },
  { name: "Maldives", flag: "🇲🇻", phone: "+960", code: "MV" },
  { name: "Mali", flag: "🇲🇱", phone: "+223", code: "ML" },
  { name: "Malta", flag: "🇲🇹", phone: "+356", code: "MT" },
  { name: "Marshall Islands", flag: "🇲🇭", phone: "+692", code: "MH" },
  { name: "Mauritania", flag: "🇲🇷", phone: "+222", code: "MR" },
  { name: "Mauritius", flag: "🇲🇺", phone: "+230", code: "MU" },
  { name: "Mexico", flag: "🇲🇽", phone: "+52", code: "MX" },
  { name: "Micronesia", flag: "🇫🇲", phone: "+691", code: "FM" },
  { name: "Moldova", flag: "🇲🇩", phone: "+373", code: "MD" },
  { name: "Monaco", flag: "🇲🇨", phone: "+377", code: "MC" },
  { name: "Mongolia", flag: "🇲🇳", phone: "+976", code: "MN" },
  { name: "Montenegro", flag: "🇲🇪", phone: "+382", code: "ME" },
  { name: "Morocco", flag: "🇲🇦", phone: "+212", code: "MA" },
  { name: "Mozambique", flag: "🇲🇿", phone: "+258", code: "MZ" },
  { name: "Myanmar", flag: "🇲🇲", phone: "+95", code: "MM" },
  { name: "Namibia", flag: "🇳🇦", phone: "+264", code: "NA" },
  { name: "Nauru", flag: "🇳🇷", phone: "+674", code: "NR" },
  { name: "Nepal", flag: "🇳🇵", phone: "+977", code: "NP" },
  { name: "Netherlands", flag: "🇳🇱", phone: "+31", code: "NL" },
  { name: "New Zealand", flag: "🇳🇿", phone: "+64", code: "NZ" },
  { name: "Nicaragua", flag: "🇳🇮", phone: "+505", code: "NI" },
  { name: "Niger", flag: "🇳🇪", phone: "+227", code: "NE" },
  { name: "Nigeria", flag: "🇳🇬", phone: "+234", code: "NG" },
  {
    name: "North Macedonia (formerly Macedonia)",
    flag: "🇲🇰",
    phone: "+389",
    code: "MK",
  },
  { name: "Norway", flag: "🇳🇴", phone: "+47", code: "NO" },
  { name: "Oman", flag: "🇴🇲", phone: "+968", code: "OM" },
  { name: "Pakistan", flag: "🇵🇰", phone: "+92", code: "PK" },
  { name: "Palau", flag: "🇵🇼", phone: "+680", code: "PW" },
  { name: "Panama", flag: "🇵🇦", phone: "+507", code: "PA" },
  { name: "Papua New Guinea", flag: "🇵🇬", phone: "+675", code: "PG" },
  { name: "Paraguay", flag: "🇵🇾", phone: "+595", code: "PY" },
  { name: "Peru", flag: "🇵🇪", phone: "+51", code: "PE" },
  { name: "Philippines", flag: "🇵🇭", phone: "+63", code: "PH" },
  { name: "Poland", flag: "🇵🇱", phone: "+48", code: "PL" },
  { name: "Portugal", flag: "🇵🇹", phone: "+351", code: "PT" },
  { name: "Qatar", flag: "🇶🇦", phone: "+974", code: "QA" },
  { name: "Romania", flag: "🇷🇴", phone: "+40", code: "RO" },
  { name: "Russia", flag: "🇷🇺", phone: "+7", code: "RU" },
  { name: "Rwanda", flag: "🇷🇼", phone: "+250", code: "RW" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", phone: "+1", code: "KN" },
  { name: "Saint Lucia", flag: "🇱🇨", phone: "+1", code: "LC" },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    phone: "+1",
    code: "VC",
  },
  { name: "Samoa", flag: "🇼🇸", phone: "+685", code: "WS" },
  { name: "San Marino", flag: "🇸🇲", phone: "+378", code: "SM" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", phone: "+239", code: "ST" },
  { name: "Saudi Arabia", flag: "🇸🇦", phone: "+966", code: "SA" },
  { name: "Senegal", flag: "🇸🇳", phone: "+221", code: "SN" },
  { name: "Serbia", flag: "🇷🇸", phone: "+381", code: "RS" },
  { name: "Seychelles", flag: "🇸🇨", phone: "+248", code: "SC" },
  { name: "Sierra Leone", flag: "🇸🇱", phone: "+232", code: "SL" },
  { name: "Singapore", flag: "🇸🇬", phone: "+65", code: "SG" },
  { name: "Slovakia", flag: "🇸🇰", phone: "+421", code: "SK" },
  { name: "Slovenia", flag: "🇸🇮", phone: "+386", code: "SI" },
  { name: "Solomon Islands", flag: "🇸🇧", phone: "+677", code: "SB" },
  { name: "Somalia", flag: "🇸🇴", phone: "+252", code: "SO" },
  { name: "South Africa", flag: "🇿🇦", phone: "+27", code: "ZA" },
  { name: "South Sudan", flag: "🇸🇸", phone: "+211", code: "SS" },
  { name: "Spain", flag: "🇪🇸", phone: "+34", code: "ES" },
  { name: "Sri Lanka", flag: "🇱🇰", phone: "+94", code: "LK" },
  { name: "Sudan", flag: "🇸🇩", phone: "+249", code: "SD" },
  { name: "Suriname", flag: "🇸🇷", phone: "+597", code: "SR" },
  { name: "Sweden", flag: "🇸🇪", phone: "+46", code: "SE" },
  { name: "Switzerland", flag: "🇨🇭", phone: "+41", code: "CH" },
  { name: "Syria", flag: "🇸🇾", phone: "+963", code: "SY" },
  { name: "Taiwan", flag: "🇹🇼", phone: "+886", code: "TW" },
  { name: "Tajikistan", flag: "🇹🇯", phone: "+992", code: "TJ" },
  { name: "Tanzania", flag: "🇹🇿", phone: "+255", code: "TZ" },
  { name: "Thailand", flag: "🇹🇭", phone: "+66", code: "TH" },
  { name: "Togo", flag: "🇹🇬", phone: "+228", code: "TG" },
  { name: "Tonga", flag: "🇹🇴", phone: "+676", code: "TO" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", phone: "+1", code: "TT" },
  { name: "Tunisia", flag: "🇹🇳", phone: "+216", code: "TN" },
  { name: "Turkey", flag: "🇹🇷", phone: "+90", code: "TR" },
  { name: "Turkmenistan", flag: "🇹🇲", phone: "+993", code: "TM" },
  { name: "Tuvalu", flag: "🇹🇻", phone: "+688", code: "TV" },
  { name: "Uganda", flag: "🇺🇬", phone: "+256", code: "UG" },
  { name: "Ukraine", flag: "🇺🇦", phone: "+380", code: "UA" },
  { name: "United Arab Emirates", flag: "🇦🇪", phone: "+971", code: "AE" },
  { name: "United Kingdom", flag: "🇬🇧", phone: "+44", code: "GB" },
  { name: "United States", flag: "🇺🇸", phone: "+1", code: "US" },
  { name: "Uruguay", flag: "🇺🇾", phone: "+598", code: "UY" },
  { name: "Uzbekistan", flag: "🇺🇿", phone: "+998", code: "UZ" },
  { name: "Vanuatu", flag: "🇻🇺", phone: "+678", code: "VU" },
  { name: "Vatican City", flag: "🇻🇦", phone: "+39", code: "VA" },
  { name: "Venezuela", flag: "🇻🇪", phone: "+58", code: "VE" },
  { name: "Vietnam", flag: "🇻🇳", phone: "+84", code: "VN" },
  { name: "Yemen", flag: "🇾🇪", phone: "+967", code: "YE" },
  { name: "Zambia", flag: "🇿🇲", phone: "+260", code: "ZM" },
  { name: "Zimbabwe", flag: "🇿🇼", phone: "+263", code: "ZW" },
];
